"""
DeepSeek Logger — Shared logging module for all Dayyakattai build scripts.
===========================================================================
Every DeepSeek script imports this and calls log_action() at each step.
Writes to:
  - logs/build_log.jsonl    (machine-readable, one JSON per line)
  - logs/build_log.txt      (human-readable running log)
  - docs/change_summary.md  (updated after each session - module-level summary)
"""
import os, json, re
from datetime import datetime, timezone

ROOT_DIR    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOGS_DIR    = os.path.join(ROOT_DIR, "logs")
JSONL_LOG   = os.path.join(LOGS_DIR, "build_log.jsonl")
TEXT_LOG    = os.path.join(LOGS_DIR, "build_log.txt")
SUMMARY_MD  = os.path.join(ROOT_DIR, "docs", "change_summary.md")

os.makedirs(LOGS_DIR, exist_ok=True)
os.makedirs(os.path.join(ROOT_DIR, "docs"), exist_ok=True)

def _now():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

def _safe(text):
    """Encode to ASCII for Windows console safety."""
    if isinstance(text, str):
        return text.encode("ascii", errors="replace").decode("ascii")
    return str(text)

def log_action(
    script: str,
    action: str,
    target_file: str = "",
    status: str = "OK",      # OK | FAIL | SKIP | INFO
    model: str = "",
    details: str = "",
    phase: str = "",
):
    """
    Log a single action to both JSONL and text log.

    Args:
        script:      Name of the calling script (e.g. 'deepseek_autofix.py')
        action:      What was done (e.g. 'FIX', 'CREATE', 'ANALYZE', 'TEST', 'COMMIT')
        target_file: Relative path to file affected (e.g. 'lib/daayakattai_board.dart')
        status:      OK | FAIL | SKIP | INFO
        model:       DeepSeek model used (e.g. 'deepseek-chat' / 'deepseek-reasoner')
        details:     Extra context (e.g. error message, issue count)
        phase:       Phase label e.g. '1.1', '2.2', '3'
    """
    entry = {
        "timestamp": _now(),
        "phase":     phase,
        "script":    script,
        "action":    action,
        "file":      target_file,
        "status":    status,
        "model":     model,
        "details":   details,
    }

    # Write JSONL
    with open(JSONL_LOG, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=True) + "\n")

    # Write human text log
    model_tag = f"[{model.replace('deepseek-','DS-')}]" if model else ""
    file_tag  = f" -> {target_file}" if target_file else ""
    icon      = {"OK": "[OK]", "FAIL": "[FAIL]", "SKIP": "[SKIP]", "INFO": "[INFO]"}.get(status, "[??]")
    line      = f"{entry['timestamp']} {icon} [{script}] {action}{file_tag} {model_tag} {details}"
    with open(TEXT_LOG, "a", encoding="ascii", errors="replace") as f:
        f.write(line + "\n")

    # Print to console
    print(_safe(f"  {icon} {action}{file_tag} {model_tag}"))
    if details:
        print(_safe(f"      {details}"))


def log_session_start(script: str, description: str):
    """Write a session header to the text log."""
    sep = "=" * 70
    header = f"\n{sep}\nSESSION: {script}\n{description}\nStarted: {_now()}\n{sep}\n"
    with open(TEXT_LOG, "a", encoding="ascii", errors="replace") as f:
        f.write(header)
    print(_safe(header))


def generate_change_summary():
    """
    Reads the JSONL log and generates/updates docs/change_summary.md.
    Groups entries by Phase -> Module -> Actions.
    """
    if not os.path.exists(JSONL_LOG):
        print("[Logger] No build log found yet.")
        return

    entries = []
    with open(JSONL_LOG, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    entries.append(json.loads(line))
                except:
                    pass

    if not entries:
        return

    # Group by phase -> file
    from collections import defaultdict
    by_phase = defaultdict(lambda: defaultdict(list))
    for e in entries:
        phase = e.get("phase") or "misc"
        file_ = e.get("file") or e.get("script", "?")
        by_phase[phase][file_].append(e)

    # Build markdown
    lines = [
        "# Dayyakattai — Master Change Log",
        "",
        f"*Auto-generated by `deepseek_logger.py` — Last updated: {_now()}*",
        "",
        "---",
        "",
        "## Summary Statistics",
    ]

    ok_count   = sum(1 for e in entries if e.get("status") == "OK")
    fail_count = sum(1 for e in entries if e.get("status") == "FAIL")
    models     = set(e.get("model","") for e in entries if e.get("model"))
    files_touched = set(e.get("file","") for e in entries if e.get("file"))

    lines += [
        f"| Metric | Value |",
        f"|---|---|",
        f"| Total logged actions | {len(entries)} |",
        f"| Successful (OK) | {ok_count} |",
        f"| Failed (FAIL) | {fail_count} |",
        f"| Files touched | {len(files_touched)} |",
        f"| Models used | {', '.join(sorted(m for m in models if m))} |",
        "",
        "---",
        "",
    ]

    phase_order = sorted(by_phase.keys(), key=lambda x: (x == "misc", x))
    for phase in phase_order:
        phase_label = f"Phase {phase}" if phase != "misc" else "Miscellaneous"
        lines.append(f"## {phase_label}")
        lines.append("")

        for file_, file_entries in sorted(by_phase[phase].items()):
            basename = os.path.basename(file_) if file_ else "?"
            lines.append(f"### `{basename}`")
            lines.append(f"*Path: `{file_}`*")
            lines.append("")
            lines.append("| Timestamp | Action | Status | Model | Details |")
            lines.append("|---|---|---|---|---|")
            for e in file_entries:
                ts      = e.get("timestamp","")[:19]
                action  = e.get("action","")
                status  = e.get("status","")
                model   = e.get("model","").replace("deepseek-","DS-")
                details = (e.get("details","") or "")[:80]
                lines.append(f"| {ts} | {action} | {status} | {model} | {details} |")
            lines.append("")

    lines.append("---")
    lines.append("*This file is auto-generated. Do not edit manually.*")

    content = "\n".join(lines)
    with open(SUMMARY_MD, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"[Logger] Change summary updated: {SUMMARY_MD}")
    print(f"         {len(entries)} actions | {ok_count} OK | {fail_count} FAIL | {len(files_touched)} files")
    return SUMMARY_MD


if __name__ == "__main__":
    generate_change_summary()
